apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.tls.hostname }}
spec:
{{ if eq .Values.clusterIssuer.type "prod" }}
  secretName: {{ .Values.tls.secret.prefix }}-prod
  issuerRef:
    name: letsencrypt-prod
{{ else }}
  secretName: {{ .Values.tls.secret.prefix }}-stag
  issuerRef:
    name: letsencrypt-stag
{{ end }}
    kind: ClusterIssuer
  commonName: {{ .Values.tls.hostname }}
  dnsNames:
  - {{ .Values.tls.hostname }}
