apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.tls.hostname }}
  namespace: {{ .Values.namespace }}
spec:
{{ if eq .Values.clusterIssuer.type "prod" }}
  secretName: {{ .Values.tls.secret.prefix }}-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{ else }}
  secretName: {{ .Values.tls.secret.prefix }}-stag
  issuerRef:
    name: letsencrypt-stag
    kind: ClusterIssuer
{{ end }}
  commonName: {{ .Values.tls.hostname }}
  dnsNames:
  - {{ .Values.tls.hostname }}
